#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing service..."

if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx configuration..."

ynh_config_remove_nginx

#=================================================
# REMOVE SYSTEMD CONFIGURATION
#=================================================
ynh_script_progression "Removing systemd service..."

ynh_config_remove_systemd

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Removing logrotate configuration..."

ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of LibreDesk completed!"
